# Generated by Django 6.0.6 on 2026-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('board_or_university', models.CharField(max_length=200)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=50)),
                ('percentage_or_cgpa', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
